### ISSUE TITLE
qsub: submit error (Unauthorized Request MSG=group ACL is not satisfied: user u0000@login-2, queue batch)

### ISSUE THREAD

**Issue by Hecmay** [intel/FPGA-Devcloud#10]
I was trying to login to S10 node with `devclou_login` scripts on DevCloud provided here: https://github.com/intel/FPGA-Devcloud/blob/master/main/Devcloud_Access_Instructions/LoginScript/devcloudLoginToolSetup.sh

Hoever qsub failed to process the request. Full error message:
```shell
running: qsub -q batch@v-qsvr-fpga -I -l nodes=s001-n138:ppn=2
qsub: submit error (Unauthorized Request  MSG=group ACL is not satisfied: user u0000@login-2, queue batch)
```

**Comment by llandis** [comment]
Looks like you might be authorized for the fpga queue. Can you type groups and let me know if you see c009-fpga? If it is not the in the list, then we will need to add you. Make sure and provide me with your u##### login ID. Thanks Larry

**Comment by Hecmay** [comment]
Thanks! It seems that I am not in that group.
```
u43471@login-2:~$ groups
u43471 c009
```
Can you please add me to the group? or do I need to apply for it somewhere?

**Comment by Hecmay** [comment]
@llandis Hi Larry, sorry to bother, but this issue is still unresolved... It seems that I am not allowed to reopen this issue.

**Comment by Prithvi-Velicheti** [comment]
I am unable to access "Arria 10 PAC Compilation and Programming - RTL AFU, OpenCL" .  
@llandis  
u75615@login-2:~$ groups
u75615 c009

Please add my userid to c009-fpga

Thanks 
Prithvi

**Comment by annasiayubu** [comment]
I`m un able to submit my job with qsub command, when I submit my work i get this message, help please!!

submit error (Unauthorized Request  MSG=user ACL rejected the submitting user: user annasiayubu@M001, queue normal

**Comment by llandis** [comment]
Can you please provide your login u##### number? It looks like you are not a member of group c009-fpga. You can type groups to check. Thanks

**Comment by annasiayubu** [comment]
Okay

**Comment by annasiayubu** [comment]
thanks for for the reply, but also sorry for my late reply,
my login (annasiayubu) or sometimes i use my email ***@***.***)
I`m doubt if i replied correctly, because I`m still new to that page

**Comment by AndreV84** [comment]
u155004@login-2:~$ groups
u155004
`0) 1.2
1) 1.2.1

Number: 1

--------------------------------------------------------------------------------------
For X2GO tunneling access. For users connected to intel firewall, copy and paste the following text in a new mobaxterm terminal:  

ssh -L 4002:s005-n003:22 colfax-intel 

For X2GO tunneling access. For users NOT connected to intel firewall, copy and paste the following text in a new mobaxterm terminal:  

ssh -L 4002:s005-n003:22 devcloud 

--------------------------------------------------------------------------------------

running: qsub -q batch@v-qsvr-fpga -I -l nodes=s005-n003:ppn=2
qsub: submit error (Unauthorized Request  MSG=group ACL is not satisfied: user u155004@login-2.aidevcloud, queue batch)
`

**Comment by AndreV84** [comment]
@llandis could you?

**Comment by AndreV84** [comment]
resolved; disregard, please

**Comment by DCupello1** [comment]
Which Arria 10 PAC Development Stack release would you like to source?
0) 1.2
1) 1.2.1

Number: 1

--------------------------------------------------------------------------------------
For X2GO tunneling access. For users connected to intel firewall, copy and paste the following text in a new mobaxterm terminal:

ssh -L 4002:s005-n007:22 colfax-intel

For X2GO tunneling access. For users NOT connected to intel firewall, copy and paste the following text in a new mobaxterm terminal:

ssh -L 4002:s005-n007:22 devcloud

--------------------------------------------------------------------------------------

running: qsub -q batch@v-qsvr-fpga -I -l nodes=s005-n007:ppn=2
qsub: submit error (Unauthorized Request  MSG=group ACL is not satisfied: user u155995@login-2.aidevcloud, queue batch)
u155995@login-2:~$
u155995@login-2:~$ groups
u155995
I also don't seem to have access to the group c009 could someone give me access to it?
