### ISSUE TITLE
qsub: submit error (Unauthorized Request MSG=group ACL is not satisfied: user u0000@login-2, queue batch) 

### ISSUE THREAD

**Issue by mahinlma** [intel/FPGA-Devcloud#11]
Reference - issue https://github.com/intel/FPGA-Devcloud/issues/10

@llandis , Could you please add me into C009-fpga, I'm not able to get - Arria 10 PAC Compilation and Programming - RTL AFU, OpenCL
Only able to login oneAPI Arria 10 node

**Comment by Hecmay** [comment]
A follow-up to this issue: I applied for the access to FPGA instance for my existing DevCloud account using the link on Intel devcloud website... 

But the devcloud team created a new account for me, and this new account does not have access to FPGA instances either.

**Comment by llandis** [comment]
User mahinlma, I see you in the system we can update you. Hecmay - can your provide full name and university, I dont see you in the database. Thanks Larry

**Comment by llandis** [comment]
User mahinlma - you have two accounts, seems like one for OneAPI for one for FPGA. Try the other account. Thanks Larry

**Comment by Hecmay** [comment]
@llandis My username: u43471. I am an intern at Intel.

**Comment by mahinlma** [comment]
Thank you @llandis

**Comment by crclayton** [comment]
Another Intel employee here, I'm also not seeing membership for group "c009-fpga". 

Name: Charles Clayton
Username: u44615

Is this a bug or have I missed a step during registration that would grant group membership by default?

**Comment by Muhammadtanveer4u** [comment]
Same issue. Here is my group command output!
u62554 c009 c009-fpga

What next?
