### ISSUE TITLE
PAC10 Batch Compilation

### ISSUE THREAD

**Issue by davidcastells** [intel/FPGA-Devcloud#14]
I'm trying to use the OpenCL flow for PAC10 (Arria10)

The quick start guide
https://github.com/intel/FPGA-Devcloud/tree/master/main/QuickStartGuides/OpenCL_Program_PAC_Quickstart/Arria%2010

explains how to login and compile for such device. The problem (as I understand) is that it works for an interactive session by using the devcloud_login interactive script.

I've tried to replicate the commands done in the script to get a batch session to compile for PAC10 without luck.

Could you provide an example to send a compilation batch job to the queue?

**Comment by davidcastells** [comment]
Sorry, I realize this was described here
https://github.com/intel/FPGA-Devcloud/tree/master/main/Devcloud_Access_Instructions#54-submitting-batch-jobs

**Comment by llandis** [comment]
Ok glad you found batch scripts in the documentation. Note there was an issue with PACSign in batch mode that was recently fixed. Let us know if it works out for you. Thanks
