### ISSUE TITLE
$OPAE_PLATFORM_ROOT and some other shell variables are not set for new users

### ISSUE THREAD

**Issue by andwari** [intel/FPGA-Devcloud#15]
Hi,
it seems that some variables like $OPAE_PLATFORM_ROOT are not set for new users. I think it would be very helpful, if you add a short sentence about sourcing the correct file (/glob/development-tools/versions/fpgasupportstack/a10/1.2/inteldevstack/init_env.sh) to set these variables.

**Comment by andwari** [comment]
Sorry, my bad! If you select the proper entry in tools_setup, everything works as expected.

**Comment by llandis** [comment]
Glad you are able to get this working!
regards
Larry
