### ISSUE TITLE
gdb Support

### ISSUE THREAD

**Issue by fellipe-leandro** [intel/FPGA-Devcloud#16]
Hello,
Is it possible to provide access to gdb in the Arria/Stratix nodes to debug opencl developed codes?

**Comment by llandis** [comment]
Checking on this ... stay tuned. Thanks Larry

**Comment by llandis** [comment]
Its on two machines: s001-n137 (Arria 10 1.2 capable) and s001-n189 (Stratix 10 2.0.1 capable). We will update on other machines. To get on specific machines: devcloud_login and select option 5.
Thanks

**Comment by fellipe-leandro** [comment]
Thanks! I'll try to use it in those nodes.
