### ISSUE TITLE
Stratix10 PAC spec

### ISSUE THREAD

**Issue by xplr1** [intel/FPGA-Devcloud#18]
Is this SX 2800  spec of stratix10 in devcloud? SOC fpga?
Share devcloud stratix10 PAC spec details

**Comment by llandis** [comment]
Did you not find the information you need here: https://www.intel.com/content/www/us/en/programmable/products/boards_and_kits/dev-kits/altera/intel-fpga-pac-d5005/overview.html

There are many documents on the Stratix 10 family of FPGAs. Start navigating from this link:
https://www.intel.com/content/www/us/en/programmable/products/stratix-series/s10/support/documentation.html
