### ISSUE TITLE
ssh devcloud permission denied

### ISSUE THREAD

**Issue by Hecmay** [intel/FPGA-Devcloud#20]
Hi, 

I cannot login to the devcloud server. I got the following error msg
```shell
$ ssh devcloud
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
ssh_exchange_identification: Connection closed by remote host
```
It seems that my account has expired. How can I renew my account? My account number is u43471.

Thanks

**Comment by Hecmay** [comment]
@llandis

**Comment by llandis** [comment]
+Terry

Hecmay:
I think you will have to sign-up again. Did you get the notification about your account expiring?

https://software.intel.com/content/www/us/en/develop/forms/devcloud-fpga-sign-up.html

Note if the account goes past the expiration date, your data is erased.

Kind Regards,
Larry

**Comment by Hecmay** [comment]
Thanks Larry. 

I did not get any notification about that.
