### ISSUE TITLE
Increase the number of hugepages available to users

### ISSUE THREAD

**Issue by GrueMaster** [intel/FPGA-Devcloud#22]
Currentl, the S10 systems limit the user to 20 hugepages:
`s001-n189:~$ sysctl vm.nr_hugepages
vm.nr_hugepages = 20`

Is there a way to increase this for the user, or can it be set to default to 256?  With some designs using multiple dma channels, we are currently maxing out at 92 hugepages, but future designs will use significantly more.

**Comment by llandis** [comment]
Changes made. We will close this one out.
Thanks
