### ISSUE TITLE
running: qsub -q batch@v-qsvr-fpga -I -l nodes=s005-n007:ppn=2 qsub: submit error (Unauthorized Request  MSG=group ACL is not satisfied: user u75615@login-2, queue batch)  

### ISSUE THREAD

**Issue by Prithvi-Velicheti** [intel/FPGA-Devcloud#32]
Dear @llandis 
Please add me to group c009-fpga
My user id is 75615. I am unable to access Intel Arria10 and Stratix10 for OpenCL.

u75615@login-2:~$ groups
u75615 c009

thanks,
Prithvi.

**Comment by pentapatisivani** [comment]
@llandis  I am facing the same issue, attaching a screenshot of the error. Can you add the node u76552 to the c009-fpga group aswell?
![Screenshot from 2021-05-26 00-52-28](https://user-images.githubusercontent.com/32356876/119556646-e9444980-bdbc-11eb-845d-e712318236ba.png)

**Comment by llandis** [comment]
is this ok for you now? Thanks

**Comment by llandis** [comment]
group access and duration fixed
