### ISSUE TITLE
Add additional devices to quartus installation

### ISSUE THREAD

**Issue by developandplay** [intel/FPGA-Devcloud#39]
Would it be possible to add devices like the Stratix V and others?
Currently since the `glob` directory is read only it is not possible for users to install additional devices.
There might be local workarounds but central installation would be the simplest approach from a user perspective.
Therefore I was wondering whether you (as admins) would consider adding more devices.

Background:
As a student powerfull (used) FPGAs are usually decently accessible but the costs for a powerful server plus the quartus license are quite prohibitive for bigger student projects.
The Arria X and Stratix X are amazing devices but for some projects it's more useful to have an FPGA that is physically accessible.
As far as I'm aware Xilinx provides a decent alternative by letting students use their AWS F1 instances which provide a version of Vivado which is not locked to device families.

**Comment by llandis** [comment]
Hi
All of the higher end (Arria 10, Stratix 10, Agilex) devices are available through the Quartus Prime Pro. The Quartus Prime Standard tools support the MAX and Cyclone familes.
Regards,
Larry

**Comment by developandplay** [comment]
Ok understood.
I guess I should have checked more carefully which families are actually supported before getting that Stratix 5 board.
I'll see if I can my hands on an Arria/Stratix 10 development board so I can replicate the project locally.
Thanks for providing this platform it's great to be able to learn about the more powerful FPGAs.
