### ISSUE TITLE
login script does not work from folder other that $HOME

### ISSUE THREAD

**Issue by Custler** [intel/FPGA-Devcloud#6]
You have to change the script to eliminate all relative references to nodes.txt file and use smth like 
**NODE_FILE_TXT=$HOME/nodes.txt**

Also you have to add 
**-d .**
at the end of qsub command to stay in same folder after invoking qsub

**Comment by elwerro** [comment]
Hello,
Thank you for your comment. The login script was updated so that it is not creating any files like nodes.txt or checknode.txt. I think that will fix that issue.

**Comment by angelsanchezInt** [comment]
Hello,
Thank you for your comment. The login script was updated so that it is not creating any files like nodes.txt or checknode.txt. I think that will fix that issue.

**Comment by llandis** [comment]
Script fixed. No more issues.
