### ISSUE TITLE
x2gosever is not supported by all nodes  

### ISSUE THREAD

**Issue by hhagiwar** [intel/FPGA-Devcloud#8]
X2goserver is not installed on all nodes listed by the devcloud_login function in devcloudLoginToolSetup.sh.

For example, s001-n137,n138 and n139 do support x2go, but  s005-n007, s001-n081, n082 ... do not support x2gosever.   If working with a node not installed x2goserver, we face an error as attaced.
![Capture](https://user-images.githubusercontent.com/12528943/79233468-dcf47a00-7ea3-11ea-8059-f58d8fbe3196.JPG)

Please make it enable on all nodes or clarify which compute nodes support x2go in the doc.

Thanks!

**Comment by dkjiang2018** [comment]
I encountered the same error as you. Have you solved this issue? Thanks

**Comment by llandis** [comment]
We adjusted the script to only put the X2Go tunneling commands when you login to X2Go machines which are: x2goNodes=("s001-n137" "s001-n138" "s001-n139" "s005-n005"). More machines will be added over time. Refer to /data/intel_fpga/devcloudLoginToolSetup.sh and look for the global variables to see supported machines. Thanks Larry
